package nlp.stanford;

import edu.stanford.nlp.process.Tokenizer;
import edu.stanford.nlp.process.TokenizerFactory;
import edu.stanford.nlp.process.CoreLabelTokenFactory;
import edu.stanford.nlp.process.DocumentPreprocessor;
import edu.stanford.nlp.process.PTBTokenizer;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.ling.HasWord;
import edu.stanford.nlp.ling.Sentence;
import edu.stanford.nlp.trees.*;
import edu.stanford.nlp.parser.lexparser.LexicalizedParser;
import org.ailab.wimfra.util.FileUtil;
import org.ailab.wimfra.util.StringUtil;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: WZP
 * Date: 15-12-23
 * Time: 下午9:11
 * To change this template use File | Settings | File Templates.
 */
public class StanfordUtil {

    /* 停用词表 */
    private static HashSet<String> stopWordSet_caseNoSensitive = null;
    private static HashSet<String> stopWordSet_caseSensitive = null;

    public static List<String> Tokenize(String setence) {
        // This option shows loading and using an explicit tokenizer
        if (StringUtil.isEmpty(setence))
            return new ArrayList<String>();
        TokenizerFactory<CoreLabel> tokenizerFactory =
                PTBTokenizer.factory(new CoreLabelTokenFactory(), "");
        Tokenizer<CoreLabel> tok = tokenizerFactory.getTokenizer(new StringReader(setence));
        List<CoreLabel> rawWords2 = tok.tokenize();
        List<String> token_list = new ArrayList<String>();
        for (CoreLabel coreLabel : rawWords2)
            token_list.add(coreLabel.toString());
        return token_list;
    }

    /**
     * 获取停用词表
     * @return
     */
    public static HashSet<String> getStopWords(boolean caseSensitive) {
        if (caseSensitive) {
            if (stopWordSet_caseSensitive != null)
                return stopWordSet_caseSensitive;
            stopWordSet_caseSensitive = new HashSet<String>();
            for (String str : stopWords)
                stopWordSet_caseSensitive.add(str);
            return stopWordSet_caseSensitive;
        }
        else {
            if (stopWordSet_caseNoSensitive != null)
                return stopWordSet_caseNoSensitive;
            stopWordSet_caseNoSensitive = new HashSet<String>();
            for (String str : stopWords)
                stopWordSet_caseNoSensitive.add(str.toUpperCase());
            return stopWordSet_caseNoSensitive;
        }
    }

    private static String[] stopWords = {
            "a",
            "about",
            "above",
            "across",
            "after",
            "afterwards",
            "again",
            "against",
            "all",
            "almost",
            "alone",
            "along",
            "already",
            "also",
            "although",
            "always",
            "am",
            "among",
            "amongst",
            "amoungst",
            "amount",
            "an",
            "and",
            "another",
            "any",
            "anyhow",
            "anyone",
            "anything",
            "anyway",
            "anywhere",
            "are",
            "around",
            "as",
            "at",
            "back",
            "be",
            "became",
            "because",
            "become",
            "becomes",
            "becoming",
            "been",
            "before",
            "beforehand",
            "behind",
            "being",
            "below",
            "beside",
            "besides",
            "between",
            "beyond",
            "bill",
            "both",
            "bottom",
            "but",
            "by",
            "call",
            "can",
            "cannot",
            "cant",
            "co",
            "computer",
            "con",
            "could",
            "couldnt",
            "cry",
            "de",
            "describe",
            "detail",
            "do",
            "done",
            "down",
            "due",
            "during",
            "each",
            "eg",
            "eight",
            "either",
            "eleven",
            "else",
            "elsewhere",
            "empty",
            "enough",
            "etc",
            "even",
            "ever",
            "every",
            "everyone",
            "everything",
            "everywhere",
            "except",
            "few",
            "fifteen",
            "fify",
            "fill",
            "find",
            "fire",
            "first",
            "five",
            "for",
            "former",
            "formerly",
            "forty",
            "found",
            "four",
            "from",
            "front",
            "full",
            "further",
            "get",
            "give",
            "go",
            "had",
            "has",
            "hasnt",
            "have",
            "he",
            "hence",
            "her",
            "here",
            "hereafter",
            "hereby",
            "herein",
            "hereupon",
            "hers",
            "herse",
            "him",
            "himse",
            "his",
            "how",
            "however",
            "hundred",
            "i",
            "ie",
            "if",
            "in",
            "inc",
            "indeed",
            "interest",
            "into",
            "is",
            "it",
            "its",
            "itse",
            "keep",
            "last",
            "latter",
            "latterly",
            "least",
            "less",
            "ltd",
            "made",
            "many",
            "may",
            "me",
            "meanwhile",
            "might",
            "mill",
            "mine",
            "more",
            "moreover",
            "most",
            "mostly",
            "move",
            "much",
            "must",
            "my",
            "myse",
            "name",
            "namely",
            "neither",
            "never",
            "nevertheless",
            "next",
            "nine",
            "no",
            "nobody",
            "none",
            "noone",
            "nor",
            "not",
            "nothing",
            "now",
            "nowhere",
            "of",
            "off",
            "often",
            "on",
            "once",
            "one",
            "only",
            "onto",
            "or",
            "other",
            "others",
            "otherwise",
            "our",
            "ours",
            "ourselves",
            "out",
            "over",
            "own",
            "part",
            "per",
            "perhaps",
            "please",
            "put",
            "rather",
            "re",
            "same",
            "see",
            "seem",
            "seemed",
            "seeming",
            "seems",
            "serious",
            "several",
            "she",
            "should",
            "show",
            "side",
            "since",
            "sincere",
            "six",
            "sixty",
            "so",
            "some",
            "somehow",
            "someone",
            "something",
            "sometime",
            "sometimes",
            "somewhere",
            "still",
            "such",
            "system",
            "take",
            "ten",
            "than",
            "that",
            "the",
            "their",
            "them",
            "themselves",
            "then",
            "thence",
            "there",
            "thereafter",
            "thereby",
            "therefore",
            "therein",
            "thereupon",
            "these",
            "they",
            "thick",
            "thin",
            "third",
            "this",
            "those",
            "though",
            "three",
            "through",
            "throughout",
            "thru",
            "thus",
            "to",
            "together",
            "too",
            "top",
            "toward",
            "towards",
            "twelve",
            "twenty",
            "two",
            "un",
            "under",
            "until",
            "up",
            "upon",
            "us",
            "very",
            "via",
            "was",
            "we",
            "well",
            "were",
            "what",
            "whatever",
            "when",
            "whence",
            "whenever",
            "where",
            "whereafter",
            "whereas",
            "whereby",
            "wherein",
            "whereupon",
            "wherever",
            "whether",
            "which",
            "while",
            "whither",
            "who",
            "whoever",
            "whole",
            "whom",
            "whose",
            "why",
            "will",
            "with",
            "within",
            "without",
            "would",
            "yet",
            "you",
            "your",
            "yours",
            "yourself",
            "yourselves",
            "-LRB-",
            "-RRB-"};
}
